### ISSUE TITLE
AguaClara Formal

### ISSUE THREAD

**Issue by jillianwhiting** [AguaClara/Small-Projects#1]
Formal dinner that would celebrate graduating seniors and the progress that the program has made. We would invite team members, faculty, staff, administrators, and alumni. It would mostly be a time for all of us to celebrate AguaClara and thank the people who make it happen. It could also be a great way to reconnect with alumni. We were thinking it could happen in the fall to catch people graduating at all times. Jonathan Harris our Community RA will help the SLs in organizing this.  A team of up to 5 SLs could help in planning this. The deadline will be the date decided for the formal.

**Comment by GPacenza** [comment]
Hey, I would like to sign up for this small project - Giancarlo Pacenza

**Comment by ashleyhe16** [comment]
add me to this!! :)

**Comment by rtang28** [comment]
Hi can I be added to this?

**Comment by JonathanDavidHarris** [comment]
Yaaay! Glad to hear guys. I’ll send you all a poll to see when we can meet to discuss the event.

**Comment by barbaraoramah** [comment]
please add me to this!

**Comment by VanessaQi** [comment]
Hi all, do we still need people for this event? Pls add me if we still do!

**Comment by jillianwhiting** [comment]
sorry this did not end up working out, but thank you all for your hard work, and we will make this happen next semester
