### ISSUE TITLE
Talent Show

### ISSUE THREAD

**Issue by jillianwhiting** [AguaClara/Small-Projects#4]
We want to have a talent during class on 10/7. We want students be acts and 2 SLs will coordinate.

**Comment by clare45** [comment]
We don't want this to be on the 10/7...

But I want to do this again with @zoemaisel even though neither of us is a STL

**Comment by zoemaisel** [comment]
10/7 is during fall break...can we do it a bit after that? Would also be nice to do it later so that the team feels more comfortable with each other. Maybe sometime in November? I would help @clare45 do this as well

**Comment by clare45** [comment]
@cheertsang @mailemccann 
ASSIGN US A MONDAY

**Comment by mailemccann** [comment]
You can have any Monday in November as of right now!! Maybe Monday before Thanksgiving? Or after? @clare45

**Comment by ericdalpe** [comment]
I would love to be assigned to this but I cannot assign myself :(
