### ISSUE TITLE
Social Events

### ISSUE THREAD

**Issue by IanCullings** [AguaClara/Small-Projects#6]
@Anishka99 and I want to host movie nights over the semester for the whole team!  These will probably be held in B14 on Friday or Saturday nights.  There will definitely be popcorn and snacks at the movie, and there could also possibly be a team dinner beforehand.

We should be able to plan these ourselves, so we don't need any other people for this project.

**Comment by jillianwhiting** [comment]
This sounds great! The team leads approve, make sure to put labels on so people know whether or not it needs more people or is already in progress

**Comment by ChingPangggg** [comment]
Can I be assigned to this :')

**Comment by IanCullings** [comment]
Update: We'll be planning more general social events for AguaClara, including but not limited to: movie nights, game nights, potlucks, team dinners, and such.  We could take 1-2 more members if people are interested.

**Comment by IanCullings** [comment]
@JonathanDavidHarris do you have any suggestions or ideas for events you want to hold as community RA?  We are here to help :)

**Comment by JonathanDavidHarris** [comment]
@IanCullings This is great! Let me know if you need any assistance from me. #CommunityRAApproved

**Comment by ChingPangggg** [comment]
Doing things in Monday night class?
Events that force people to talk? 
Friendship speed-dating->coffee chat or lunch
Game night at B14
Scavenger hunt (Agualara themed?)
Ice-skating
Rock-climbing night?
Escape room (?) at design lab
Trivia night
Secret Santa
Ask Cheer about open Monday night classes
Team dinner
Aguaclara olympics

**Comment by jillianwhiting** [comment]
game night was great!
